export const BLOGS = [
  {
    id: 0,
    title: "Node.js and Event Loop",
    header_img:
      "https://images.pexels.com/photos/556666/pexels-photo-556666.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    description: "Some description blah blah blah blah blah blah blah",
    content: "Some content",
    author: "Amogh Dixit",
    read_time: "5",
    publishedAt: "20 Oct. 2001",
    likes: 0,
    comments: [],
  },
  {
    id: 1,
    title: "Node.js and Event Loop",
    header_img:
      "https://images.pexels.com/photos/556666/pexels-photo-556666.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    description: "Some description blah blah blah blah blah blah blah",
    content: "Some content",
    author: "Amogh Dixit",
    read_time: "5",
    publishedAt: "20 Oct. 2001",
    likes: 0,
    comments: [],
  },
  {
    id: 2,
    title: "Node.js and Event Loop",
    header_img:
      "https://images.pexels.com/photos/556666/pexels-photo-556666.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    description: "Some description blah blah blah blah blah blah blah",
    content: "Some content",
    author: "Amogh Dixit",
    read_time: "5",
    publishedAt: "20 Oct. 2001",
    likes: 0,
    comments: [],
  },
  {
    id: 3,
    title: "Node.js and Event Loop",
    header_img:
      "https://images.pexels.com/photos/556666/pexels-photo-556666.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    description: "Some description blah blah blah blah blah blah blah",
    content: "Some content",
    author: "Amogh Dixit",
    read_time: "5",
    publishedAt: "20 Oct. 2001",
    likes: 0,
    comments: [],
  },
  {
    id: 4,
    title: "Node.js and Event Loop",
    header_img:
      "https://images.pexels.com/photos/556666/pexels-photo-556666.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    description: "Some description blah blah blah blah blah blah blah",
    content: "Some content",
    author: "Amogh Dixit",
    read_time: "5",
    publishedAt: "20 Oct. 2001",
    likes: 0,
    comments: [],
  },
  {
    id: 4,
    title: "Node.js and Event Loop",
    header_img:
      "https://images.pexels.com/photos/556666/pexels-photo-556666.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    description: "Some description blah blah blah blah blah blah blah",
    content: "Some content",
    author: "Amogh Dixit",
    read_time: "5",
    publishedAt: "20 Oct. 2001",
    likes: 0,
    comments: [],
  },
];
